
// Ans 6

// let username = "admin";;
// let password = "1234";
// let input_username = "admin";
// let input_password = "1234";
// if(username==input_username && password==input_password){
//     console.log("Login successful")
// }else if(username==input_username && password!=input_password){
//     console.log("Invalid password");
// }else if(username!=input_username && password==input_password){
//     console.log("Invalid Username");
// }else{
//     console.log("Login Failed");
// }